AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - vendor/**/*
    - benchmark/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/**/*_test.rb'
    - 'lib/clsx/helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*_test.rb'
    - 'lib/clsx/helper.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/clsx/helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/clsx/helper.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/clsx/helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/clsx/helper.rb'
    - 'test/**/*_test.rb'

Metrics/BlockNesting:
  Exclude:
    - 'lib/clsx/helper.rb'

Lint/LiteralAsCondition:
  Exclude:
    - 'test/**/*_test.rb'
